"""create kpi_material table

Revision ID: 0e7cff009064
Revises: 44e690812cce
Create Date: 2025-05-06 14:03:33.000471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e7cff009064'
down_revision = '44e690812cce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_guid', sa.String(length=100), nullable=True),
    sa.Column('batch_name', sa.String(length=255), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('batch_act_start', sa.DateTime(), nullable=True),
    sa.Column('batch_act_end', sa.DateTime(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('material_name', sa.String(length=255), nullable=True),
    sa.Column('material_code', sa.String(length=100), nullable=True),
    sa.Column('setpoint_float', sa.Float(), nullable=True),
    sa.Column('actual_value_float', sa.Float(), nullable=True),
    sa.Column('source_server', sa.String(length=100), nullable=True),
    sa.Column('rootguid', sa.String(length=100), nullable=True),
    sa.Column('order_id', sa.String(length=100), nullable=True),
    sa.Column('event_id', sa.String(length=100), nullable=True),
    sa.Column('batch_transfer_time', sa.String(length=100), nullable=True),
    sa.Column('formula_category_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kpi_material')
    # ### end Alembic commands ###
