"""Updated KPI model

Revision ID: 44e690812cce
Revises: 
Create Date: 2025-03-20 16:32:32.805271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e690812cce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_guid', sa.String(length=50), nullable=False),
    sa.Column('batch_name', sa.String(length=255), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('batch_act_start', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_guid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kpi')
    # ### end Alembic commands ###
